### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by hakobyannairi** [DavidDavidsonDK/Chess-Board-Recognition#1]
Get accuracy
- overall
- per class (e.g. accuracy of pawn recognition)
- class to class with a table (e.g. how many pawns are classified as bishops, queens etc..)

**Comment by DavidDavidsonDK** [comment]
overall: 98,36%
Per class:
class bb : 0.967479674796748
class bk : 0.961038961038961
class bn : 0.98
class bp : 0.9968944099378882
class bq : 0.8586956521739131
class br : 0.9836065573770492
class wb : 0.957983193277311
class wk : 0.9615384615384616
class wn : 1.0
class wp : 1.0
class wq : 0.9340659340659341
class wr : 1.0
class empty : 1.0

**Comment by DavidDavidsonDK** [comment]
<img width="463" alt="screen shot 2018-11-27 at 22 03 03" src="https://user-images.githubusercontent.com/28263496/49101769-71027900-f290-11e8-9ef6-e5bdda9a4c36.png">
